version: "3.5"
services: 
    web:
        build: .
        command: ./test
        ports:
            - target: 8080
              published: 80
        networks: 
            - mynet
        volumes:
            - type: volume
              source: myvol
              target: /code
networks: 
    mynet:
volumes: 
    myvol: